### ISSUE TITLE
Indexer not picking up genrule file sources

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [bazelbuild/tulsi#149]
Hello there,

I am using the following Buildfile with Tulsi

```
genrule(
    name = "GeneratedMocks",
    srcs = glob(["Sources/**/*.swift"]),
    outs = ["Generated/GeneratedMocks.swift"],
    cmd = "mockolo -srcs $(SRCS) -d $@ -i MyLib"
)

swift_library(
    name = "MyUnitTestsLib",
    module_name = "MyUnitTestsLib",
    srcs = glob(["Tests/UnitTests/**/*.swift"]) + [":GeneratedMocks"],
    deps = [
        ":MyLib"
    ]
)
```

I can see that the generated files are being linked to the project correctly because I am able to run my Unit Tests with generated Mocks, and the tests pass, XCode however is not indexing these files and gives me warnings the mock classes do not exist.

How can I make sure XCode's indexer is picking up these generated files?

**Comment by tinder-maxwellelliott** [comment]
Confirmed this is happening with most recent HEAD https://github.com/bazelbuild/tulsi/commit/1abf3e770de2a8f3289c7875da45bee765fefdf8

**Comment by tinder-maxwellelliott** [comment]
Okay I made a branch off of the example repo for Bazel and added a genrule to the sample app, you can find the branch here: https://github.com/tinder-maxwellelliott/examples/tree/tulsi_bazel_gen_issues

You can see that the file is greyed out and not visible to users in the project, its looks like it is linked to the indexer

<img width="1410" alt="Screen Shot 2020-06-04 at 10 47 40 AM" src="https://user-images.githubusercontent.com/56700854/83793245-21ed8f00-a651-11ea-8f76-931649e7a57e.png">

**Comment by tinder-maxwellelliott** [comment]
@DavidGoldman I am looking into possibly taking this on as developers here would like to see generated code inline inside of Xcode. From what I can see in the code we are creating a symlink to the the output directory. Should we actually run the genrules one time before we create the symlink? I cannot see how Xcode could find those files via Symlink at project generation time, they must exist before we open Xcode.

Am I incorrect in my assumptions here?

**Comment by cpsauer** [comment]
Hey @tinder-maxwellelliott, @DavidGoldman, I got curious about the generated sources issue, since @tinder-maxwellelliott  commented about it on that #164, where I'd commented a workaround to made external files work. And maybe I'll need it someday, who knows :)

Things definitely seem broken around generated files. But I think I've figured out what's going on--or at least how I think it should work, what's going on, an (ugly) workaround, and how you'd fix it right.

I started by grabbing some code from @tinder-maxwellelliott's example project to test things out. My setup was just a simple generated hpp file being included in a cc_library dep of an ios_framework. I was shocked that it initially worked exactly as I'd expect: I could cmd click into the generated files and see them. Awesome! (I wasn't trying to put them in the project navigator, since I don't want to encourage editing the generated files, just viewing them while I'm using them.) But then I ran a clean and rebuild and problems started to show up. Suddenly I was getting "file not found" errors and couldn't cmd click through.

So here's what was going on: The Xcode project was configured to find the generated files through a path for the wrong platform. bazel-bin is being added as a header search path, Xcode-project wide, as is bazel-genfiles (which I think is an old, deprecated bazel symlink). The problem is that the [bazel-bin symlink isn't platform specific.](https://docs.bazel.build/versions/master/output_directories.html) At least on my system, it was always pointing to `execroot/__main__/bazel-out/darwin-fastbuild/bin`. So iOS targets end up looking for macOS (darwin) sources; that's not good! It had worked initially because I'd first generated the file as a test--with the platform defaulting to macOS. So the iOS targets were seeing the file I'd generated for macOS.

IMO bazel-bin probably shouldn't be included in the header search paths. Instead, targets should search the headers for the generated output directories for their own platforms. So instead of `bazel-bin`, you'd search `bazel-out/<expand to relevant platforms>/bin`. (I couldn't quickly find where in the Tulsi codebase bazel-bin was being added, or I'd link to it here.) If you still wanted to have a single generated header search path for all platforms (and we probably shouldn't) then you could replace `bazel-bin` with the equivalent of `bazel-out/*/bin`--though I don't know of a way to make Xcode expand that wildcard.

Horrible hack for the meantime: Erm, I kinda feel like a bad person for posting this, but if you're desperate to make things work short term, you can take advantage of the extra, unused, bazel-genfiles symlink. Just create it, linking to the bazel-bin directory for the platform you're currently working on, and things will work. In my case, that was running `ln -s bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-2c7291cd6708/bin bazel-genfiles` from the project root. But please, at least for the sake of protobufs, let's fix generated files better than this long term. And in the meantime, if you come up with a less bad workaround, lmk. [Other alternatives I thought of were worse: Manually editing the header search path in the generated Xcode project each time, manually building all the generated sources for the wrong platform, etc.]

**Comment by cpsauer** [comment]
Related: While spinning up a PR for something else, I got reminded of this, seeing all the `bazel-genrule` references in the code. I think that symlink is long retired ([since 1.0?](https://opendev.org/opendev/gerrit/commit/1c04c59e80838a9c3d72bfbabdb5d64cd0ac5c55)) and probably the generated file logic needs an overall revamp.

**Comment by cpsauer** [comment]
Related: While spinning up a PR for something else, I got reminded of this, seeing all the `bazel-genrule` references in the code. I think that symlink is long retired ([since 1.0?](https://opendev.org/opendev/gerrit/commit/1c04c59e80838a9c3d72bfbabdb5d64cd0ac5c55)) and probably the generated file logic needs an overall revamp.

**Comment by tinder-maxwellelliott** [comment]
It would be amazing to have this fixed, other options are not nearly as Bazel-ey, like forking the local and CI build experience by generating sources into certain directories locally, but not doing that in CI.

**Comment by cpsauer** [comment]
Yeah, I agree. But I should land the other PR first. Everything's a bit entangled--and much of the searching points into the execroot, which is a huge trap since it's only a temporary sandbox that's torn down on rebuild... So if you run another build, or build a subset of your targets, everything breaks in subtle ways. (See https://github.com/bazelbuild/tulsi/issues/164. Also just fixed that in the Android Plugin.)

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
