### ISSUE TITLE
symbol reference not working in jetbrains appcode

### ISSUE THREAD

**Issue by fisheye-123** [bazelbuild/tulsi#200]
I am a big fan of jetbrains product line, I am already using intellij/clion/androidstudio for different purposes, I really want to use appcode for my ios development. Here's the big problem I got so far, if I have a swift_library, let's say A, which depends on another swift_library(B), then use appcode to open xcodeproj files generated by tulsi, B's symbols referenced in A can not be correctly recognized by AppCode, but xcode can reference them correctly. Things are the same if you change B to objc_library. should it be considered as a bug in AppCode or am I missing some secret configuration?

**Comment by fsmorygo** [comment]
Hello. I am a developer from AppCode team. Yes, I confirm this as a bug in AppCode. `$(PROJECT_FILE_NAME)` build setting was resolved incorrectly. There is an issue in our tracker: https://youtrack.jetbrains.com/issue/OC-21195

The fix is in development branch at the time I write this comment and will be released in one of upcoming updates.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
