### ISSUE TITLE
Create a BUILD file & Rule for Tulsi

### ISSUE THREAD

**Issue by steeve** [bazelbuild/tulsi#39]
It would be awesome if Tulsi shipped a `BUILD` file in its repository so that we could run the code generator directly from a Bazel target, such as when new files are added to a project.

Perhaps it could build only the command line version of Tulsi?

**Comment by StevenEWright** [comment]
Hey Steeve,

Sorry if I’m misunderstanding your question - but if you’re looking to build Tulsi from the command line I have a little one-liner shell script at home that does just that and installs it in /Applications using xcodebuild. I’d be happy to paste it here / in a gist if that’s all you need?

**Comment by dolphineye** [comment]
Hi Steven,

What Steeve means is that he wants to be able to build Tulsi with Bazel. The idea is that we want to generate an XCode project using a sh_binary target (or something similar). We want to avoid our developers to manually download and build Tulsi to generate an XCode project.

Thank you in advance for your help.

Regards

**Comment by steeve** [comment]
@StevenEWright I'm looking at building & running Tulsi (awesome tool, btw), directly from a Bazel target.

Ideally a `tulsi()` rule would be even better.

**Comment by steeve** [comment]
Exactly like `rules_go` does with a similar tool, gazelle: https://github.com/bazelbuild/bazel-gazelle#id3

```python
load("@bazel_gazelle//:def.bzl", "gazelle")

gazelle(
    name = "gazelle",
    prefix = "github.com/example/project",
)
```

**Comment by StevenEWright** [comment]
Just TBC, I don't speak for Tulsi... I'm just a regular user like you.

I think I understand what you're asking for... do you want to generate XCode projects with `blaze build` the way things used to work with the `xcode_proj` rule? This may be doable with some custom build rules that call out to a script... but let me ask some clarifying questions because some of the things you're saying are confusing me....

> What Steeve means is that we want to be able to build Tulsi with Bazel instead of using XCode (or xcodebuild) to do so.

I'm not clear what you mean by this... it doesn't sound like you actually care about how Tulsi itself gets built... do you?

> The idea is that we would like our developers to be able to generate their XCode projects using an sh_binary target (or something similar) if that's possible.

This statement is what I based my understanding of what you're trying to do on.

So Tulsi [already includes a script to do this](https://github.com/bazelbuild/tulsi/blob/master/src/tools/generate_xcodeproj.sh) and creating a custom rule to invoke the script seems reasonable, like you're implying. It would probably just need a reference to the tulsiproj folder.

Is there a reason doing this through bazel is desirable instead of just having a small shell script? At home I have a script called xcode.sh in the root of my workspace which invokes Tulsi using the above mentioned script to create the Xcode project, and opens the resulting project. I find it convenient, and I'd be happy to share it with you?

> Exactly like rules_go does with a similar tool, gazelle:

I haven't seen this project before. Interesting. The description says:

> Gazelle is a build file generator for Go projects. It can create new BUILD.bazel files for a project that follows "go build" conventions, and it can update existing build files to include new files and options.

But the "equivalent" functionality for us would be to auto-generate `BUILD` files with ios_*, objc_*, swift_* rules... have I misunderstood what their tool does? It doesn't sound like this is what you're actually asking for, is it?

Thanks for bearing with my questions... hopefully I can help?

**Comment by steeve** [comment]
Thanks for clarifying Steven!

To be clear myself, I am not talking about what gazelle does. I'm talking about the ability to download, build and run it directly as a Bazel rule:
> After adding this code, you can run Gazelle with Bazel.
> ```
> bazel run //:gazelle
> ```

The `generate_xcodeproj.sh` script you're mentioning requires an already built `Tulsi.app`. What we're trying to achieve is what `rules_go` does with gazelle:
- download Tulsi
- build Tulsi
- run Tulsi to generate the `xcodeproj`

On a side no it's kind of ironic that Tulsi uses `xcodebuild` as its build system instead of Bazel, but that's another story.

So far we've come up with a pretty small `BUILD` file that builds the app:

`BUILD.tulsi`
```python
load("@build_bazel_rules_apple//apple:macos.bzl", "macos_application")
load("@build_bazel_rules_apple//apple:swift.bzl", "swift_library")

swift_library(
    name = "TulsiGenerator_lib",
    module_name = "TulsiGenerator",
    srcs = glob(["src/TulsiGenerator/**/*.swift"]),
    swift_version = 3,
)

swift_library(
    name = "Tulsi_lib",
    module_name = "Tulsi",
    srcs = glob(["src/Tulsi/**/*.swift"]),
    swift_version = 3,
    deps = [
        ":TulsiGenerator_lib",
    ],
)

macos_application(
    name = "Tulsi_app",
    bundle_id = "com.google.Tulsi",
    bundle_name = "Tulsi",
    infoplists = [
        "src/Tulsi/Info.plist",
    ],
    deps = [
        ":Tulsi_lib",
    ]
)
```

**Comment by StevenEWright** [comment]
Ah! Yes, thank you, that's much clearer for me now!

> download Tulsi

Have you tried using the [new_http_archive](https://docs.bazel.build/versions/master/be/workspace.html#new_http_archive) rule with your build file and one of the github zips? (Like the [master/head zip](https://github.com/bazelbuild/tulsi/archive/master.zip), for example?)

The docs say:

> Downloads a compressed archive file, decompresses it, and creates a Bazel repository by combining the archive with the provided BUILD file.

This sounds like exactly what you're looking for for this step? I haven't tried it myself yet.

> build Tulsi

Sounds like this is perfectly reasonable based on what you already have. (the `Tulsi_app` target in your BUILD file).

> run Tulsi to generate the xcodeproj

Would a small custom rule with a `run` action let you use the output of the `build Tulsi` step above to do what you want? (example [here](https://github.com/bazelbuild/examples/blob/master/rules/actions_run/execute.bzl))

> On a side note it's kind of ironic that Tulsi uses xcodebuild as its build system instead of Bazel, but that's another story.

This probably has a few simple explanations. For one thing, there is the bootstrapping issue. Since Tulsi *is* the tool used to create xcodeproj files, and since it's often desirable to have an xcodeproj for development (that's Tulsi's raison d'etre after all), how would you create an xcodeproj for the Tulsi code itself if your local version of Tulsi was broken and you didn't have a stand-alone xcodeproj? (like, because you are working on it, for example). Second, I think Swift support was only "recently" added in rules_apple. All just guesses.

**Comment by nglevin** [comment]
Steven I think has done a great job of laying out the options as they exist right now.

Speaking as a member of the Apple Frameworks tooling team that spends a fair amount of time on Tulsi, my personal desire would be for this feature to rest on two things:

1) Be able to build Tulsi on Swift without a Mac, avoiding the constraint of needing to test Tulsi and Xcode project generation on Mac hardware.

2) See how we could make incremental progress towards that goal, first.

Having a rule (and _de facto_ test) for Tulsi project generation would be fantastic. That's been a requested feature from other clients.

The biggest challenges are capacity; not only developer hours allocated to the problem, but how we could build a rule like this that could run at scale.

I think it's possible, but I'm not sure how soon it could happen.

Personally, I've only started to explore the guts of the Swift compiler frontend. Swift Foundation has its own thorns, and Tulsi itself still depends on NSDocument to a significant degree for UI and data serialization, though we've found issues with NSDocument that might have us moving away from that in the long term.

(Do not take this as the official word, yet!)

**Comment by dierksen** [comment]
OK, BUILD rules for Tulsi are out now.

Should be able to build it using `bazel build //:tulsi`. We're not set up for `bazel run` support yet, but one step at a time 😄.

**Comment by steeve** [comment]
Haha ! This is great guys!

**Comment by steeve** [comment]
Ideally the step to regen an xcodeproj would be the one to run, so that when build files are changed it's super easy and does not involve starting a gui

**Comment by dierksen** [comment]
For sure. It will probably be functionally identical to [the existing script](https://github.com/bazelbuild/tulsi/blob/master/src/tools/generate_xcodeproj.sh), but won't require you to have already built Tulsi before using it.

**Comment by DavidGoldman** [comment]
Closing as this is resolved on HEAD, see the `build_and_run.sh` script.

**Comment by cpsauer** [comment]
For folks reading, more discussion in https://github.com/bazelbuild/tulsi/issues/187
