### ISSUE TITLE
Tusli fdebug-prefix-map Flag Causes Recompile

### ISSUE THREAD

**Issue by przemeklach** [bazelbuild/tulsi#41]
I posted the original issue here: https://groups.google.com/forum/#!topic/bazel-discuss/GWM6igeQJX4.

It appears that this commit: https://github.com/bazelbuild/tulsi/commit/d06c276c6cf7bfe614ca0309523f65778f28b424 introduced a --copt that forces Xcode to recompile my applications even after building them on the command line using hazel build -c dbg src/main/myap. 

My current work around is to use a Tusli version that is based on a commit prior to the one above.

**Comment by nglevin** [comment]
I do want to get rid of that flag, but that's contingent on having more Tulsi users adopt the fixes to properly export dSYM bundles through the latest Apple Bazel rules, which recently landed in that repo.

The flag was added for the sake of another client. We've had more conversations about keeping rules updates in sync with Tulsi lately, so hopefully that will happen sooner than later...

**Comment by nglevin** [comment]
...looks like it might be sooner after all.

**Comment by robbiemc** [comment]
Hey @nglevin, is there any update on this?

Also, you mentioned that Tulsi users will have to do something to properly export dSYM bundles. Is that a change that you expect all Tulsi users will need to make, or is it specific to just a couple users?

**Comment by nglevin** [comment]
Still discussing what needs to be done upstream of Tulsi so that you don't need to assign the same -fdebug-prefix-map flag.

Though you might still need to pass some flag to keep it consistent with Tulsi, for normalizing the debug info. We're still working out the details.

**Comment by nglevin** [comment]
As for dSYM bundles, that's largely for portable debug information when you've built on macOS on one machine, but you want to debug on another machine. Otherwise the DWARF debug information is all found in absolute paths to .o files on the machine where you built the binaries.

When I wrote that last update, I was considering if it was for the best to make dSYM bundles mandatory for all Tulsi builds, but their generation does add to our linking time. (...understandable given that dsymutil has to navigate clang's AST cache to recover DWARF information...)

**Comment by przemeklach** [comment]
Hi @nglevin. I'm on Bazel 0.12.0 and the latest Tusli. Still have this issue. Do you have any more information on this? Thank you.

**Comment by nglevin** [comment]
My last day at Google will be May 2nd, so there's not much more that I can do, but explain your problem.

This particular usage of -fdebug-prefix-map is exclusive to the Tulsi you see that works with Bazel, in Github.

Without it, you wouldn't have a means of debugging sources with breakpoints without using lldbinit via target.source-map or dSYMs. Tulsi's use of target.source-map is fragile and very dependent on the implementation of Xcode's lldb-rpc-server, and there's no guarantee that will remain stable in a future Xcode release. As for dSYMs, that's honestly the best supported solution for debugging that Xcode has for how Bazel builds Apple binaries, and it's been recommended for that purpose. Unfortunately, there's pushback by clients in using dSYMs for debugging because they add to the overall link time during a build, and if you're experiencing long compile times, the dSYMs will inevitably add to that.

If you're trying to `bazel build X` independent from Tulsi, you'll have to use the same -fdebug-prefix-map argument with the same arguments that Tulsi uses to keep your debugging the same as before, which avoids invalidating the Bazel cache and causes a recompile.

In the case of Tulsi, and I do mean the Tulsi that works specifically with Bazel, you need -fdebug-prefix-map=$(bazel info execution_root)=$(path_to_your_primary_workspace) without trailing slashes for an external Bazel command to match the arguments perfectly.


In a more optimistic time, I was hoping that the Apple supported dSYM route could be used for all uses of Tulsi. Today, that cannot pan out, due to a focus on build times.

**Comment by nglevin** [comment]
For more background, I was previously hinting at our use of this feature; https://github.com/bazelbuild/tulsi/blob/d56e22cbe15f3ee839ff9d854bdef1fe0dce113a/src/TulsiGenerator/Scripts/bazel_build.py#L811

I don't know if the Github rules take advantage of this yet, but it adds an argument; `-fdebug-prefix-map=$(blaze info execution_root)=.`.

Its adoption is a bit slowed down by how swiftc doesn't have -fdebug-prefix-map, and needs to do some additional contortions to remap every path in the debug info to redirect to your primary workspace. And then if you're not using dSYMs, you have to use lldbinit, which is fragile (see previous post) and has many bad side effects...

Anyway, that's probably more of a response than you were expecting. But, start to finish, that's the why and how and when.

**Comment by nglevin** [comment]
Finally, for -fdebug-prefix-map support in Swift, Tony's been pushing that in my absence (and frequent hospital visits*). It hasn't seen any responses or traction outside of ourselves, though.

https://forums.swift.org/t/modifying-debug-info-for-hermetic-distributable-builds/11780

* - (Life's been interesting for me, but that's wholly independent of this issue at hand.)

**Comment by nglevin** [comment]
Closing issue as the solution is, essentially to have your bazel build on the command line match the same flags as Tulsi's. -fdebug-prefix-map is one, compilation_mode (dbg or opt) is another, and so on.

The closer the better, to avoid invalidating as much of the Bazel cache as you can.

**Comment by przemeklach** [comment]
@nglevin Thank you for the in depth explanation. 

I wish you all the best.
