### ISSUE TITLE
Why refactor group/filereference structure from folder groups to dummy groups?

### ISSUE THREAD

**Issue by xinzhengzhang** [bazelbuild/tulsi#55]
Tulsi will generate a project with dummy groups which cause create file or directory(Add File to xxx & New Group) in xcode on the root path by default. 

And I found that there was a refactor for group/filereference structure(https://github.com/bazelbuild/tulsi/commit/68c0b2089939805b2a7c42c3b6c7bf941c9c3dc2)
Why consider using dummy group instead of real one?

![image](https://user-images.githubusercontent.com/1487445/43317147-4a866098-91ce-11e8-80c4-98f0702ba873.png)

**Comment by DavidGoldman** [comment]
The recommended workaround for now is to use `File -> Duplicate` when creating new files.

This issue is a complicated one. Using dummy groups and having per-file relative-paths from the `mainGroup` allows the following:

- Modify the paths on per-file basis without needing to create new groups. This allows us to resolve files from the Bazel execution-root (`tulsi-workspace` symlink) while still keeping them in the same folder and is also used internally to do other remappings. This probably comes down to personal preference.
- Prevents an issue where Xcode elides files of the same name where one file exists and the other one doesn't, which is often the case for generated files. i.e. if you have a file within nested groups called `Library.m` and another generated `Library.m` in a separate path, when the generated `Library.m` doesn't exist, trying to open that file in Xcode will actually bring you to the non-generated one.

Unfortunately, the current solution has the side effect of creating new files from the `mainGroup` path.

**Comment by xinzhengzhang** [comment]
Thanks for replying.
Creating new files is much more frequently than the behavor that caused this issus in my case.
And I will patch it on my fork ╮(╯▽╰)╭
