### ISSUE TITLE
Tulsi does not read --test_env flags in .bazelrc when creating xcodeproj

### ISSUE THREAD

**Issue by ravimandala** [bazelbuild/tulsi#67]
Our team uses a `.bazelrc` which includes build and test flags. Tulsi picks up the `.bazelrc` file when pointed to in **'Build' startup options** with a `--bazelrc=.bazelrc` but it is **not** reading `--test-env` flags and **not** setting them on test targets. As a result, the flags might be used during bazel build in Xcode but they are not effective while running individual tests from Xcode.

@DavidGoldman @reinhillmann @dierksen, Can you please take a look?

**Comment by dierksen** [comment]
Unfortunately, in order to get the Xcode integration, we have to let Xcode run the tests, so bazel is left out of the loop here, including anything in the .bazelrc file.

The best workarounds we have are to add the EnvironmentVariables to your tulsi config files (as mentioned in #66 ) or to run `bazel test`.
