### ISSUE TITLE
Tulsi doesn't pass apple_generate_dsym anymore

### ISSUE THREAD

**Issue by steeve** [bazelbuild/tulsi#68]
Hi all,

Apparently Tulsi doesn't pass `--apple_generate_dsym` anymore, which prevents `.dSYM` generation, which in turn prevents breakpoint support.
When manually adding `--apple_generate_dsym` to the build options, breakpoints work properly.

Is there a reason this was removed ?

Thanks!

**Comment by DavidGoldman** [comment]
Tulsi should pass `--apple_generate_dsym` for [release builds](https://github.com/bazelbuild/tulsi/blob/3cc36fa2ced46046723529e597916e013cfd402e/src/TulsiGenerator/BazelSettingsProvider.swift#L126) and [builds](https://github.com/bazelbuild/tulsi/blob/3cc36fa2ced46046723529e597916e013cfd402e/src/TulsiGenerator/BazelSettingsProvider.swift#L122) for targets containing Swift.

**Comment by steeve** [comment]
I was testing on this project: https://github.com/ffreling/bazelide

**Comment by steeve** [comment]
Also, I'm not sure dsyms are generated when only specifying `-c dbg`

**Comment by DavidGoldman** [comment]
Thanks, I'm able to reproduce it this with the example project. Looking into it...

**Comment by DavidGoldman** [comment]
This is due to 86b1848: Tulsi no longer supports `swift_library` from [rules_apple](https://github.com/bazelbuild/rules_apple), please use `swift_library` from [rules_swift](https://github.com/bazelbuild/rules_swift) instead ([your usage](https://github.com/ffreling/bazelide/blob/c46dedc2a8ec3326796fd97993e6cb4ad64a298a/demo/ios/BUILD.bazel#L2)).

**Comment by steeve** [comment]
Confirmed @DavidGoldman, that was it.
Sorry for the noise, everything works fine now.
